---
name: "Run Ruff"
description: "Lint code with Ruff. Config read from pyproject.toml"

inputs:
  python_version:
    description: "Python version to use"
    required: true
    default: "3.10"
  dev_requirements_path:
    description: "Path to a dev-requirements.txt file. Must be hashed!"
    required: false

runs:
  using: composite
  steps:
    - id: setup
      name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: "pip"

    - id: install
      name: Install Ruff
      env:
        dev_requirements_path: ${{ github.action_path }}/requirements.txt
      shell: bash
      run: >-
        pip3 install
        --require-hashes
        -r ${{ inputs.dev_requirements_path || env.dev_requirements_path }}

    - id: check
      name: Lint code
      shell: bash
      run: ruff check .
