---
name: 'Build Docker image'
description: 'Build Docker image from sources'

inputs:
  image_name:
    description: 'Name of the image to build and release (eg. ghcr.io/seravo/wordpress)'
    required: true
  tag:
    description: 'Tag of the image to build and release (eg. latest)'
    required: true
    default: "latest"
  path:
    description: 'Build path for Docker (default: .)'
    required: true
    default: '.'
  dockerfile:
    description: 'Name of Dockerfile'
    required: true
    default: 'Dockerfile'
  cache:
    description: "Use cache"
    required: true
    default: "yes"
  default-cache:
    description: "Use cache from input image"
    required: true
    default: "yes"
  args:
    description: 'Additional arguments for Docker build. (eg. --build-arg NAME="NAME")'
    required: true
    default: ''

outputs:
  image-id:
    description: 'Docker Image ID for the image'
    value: ''

runs:
  using: composite
  steps:
    - id: docker-build-setup
      name: 'Setup a customer builder'
      shell: bash
      run: |
        docker buildx create \
          --name seravo-customer-builder \
          --driver docker-container

    - id: pull-git-tags
      if: ${{ github.ref_type != 'tag' }}
      name: 'Pull tags from git'
      shell: bash
      run: git fetch --tags

    - id: read-git-version
      name: 'Read version information with git'
      shell: bash
      run: echo "version=$(git describe --always)" >> $GITHUB_OUTPUT

    - id: read-features
      name: Read repository features
      uses: seravo/actions/features@v2.0.0

    - id: semver
      name: Parse version information
      uses: Seravo/actions/semver@v2.0.0
      with:
        version: ${{ github.ref_name }}
      if: ${{ github.ref_type }} == 'tag'

    - id: docker-build
      name: 'Build new image'
      env:
        IMAGE: ${{ inputs.image_name }}:${{ inputs.tag }}
        FULL: ${{ steps.semver.outputs.full }}
        MAJOR_MINOR: ${{ steps.semver.outputs.major_minor }}
        MAJOR: ${{ steps.semver.outputs.major }}
      run: |
        if [ -n "${FULL}" ]
        then
          TAG_ARGS="--tag ${{ inputs.image_name }}:v${FULL} --tag ${{ inputs.image_name }}:v${MAJOR_MINOR} --tag ${{ inputs.image_name }}:v${MAJOR}"
        else
          TAG_ARGS=""
        fi

        docker buildx --builder seravo-customer-builder build \
          --label "org.opencontainers.image.revision=${{ github.sha }}" \
          --label "org.opencontainers.image.version=${{ steps.read-git-version.outputs.version }}+${{ github.run_number }}.${{ github.run_id }}.${{ github.run_attempt }}" \
          --label 'com.seravo.features=${{ steps.read-features.outputs.features }}' \
          -f "${{ inputs.path }}/${{ inputs.dockerfile }}" \
          ${{ inputs.args }} \
          ${{ inputs.cache == 'no' && '--no-cache' || '' }} \
          ${{ inputs.default-cache == 'yes' && format('--cache-from {0}', env.IMAGE ) || '' }} \
          --load \
          --tag "${{ env.IMAGE }}" \
          ${TAG_ARGS} \
          "${{ inputs.path }}"
      shell: bash
