---
name: 'Build Docker image'
description: 'Build Docker image from sources'

inputs:
  image:
    description: 'Name for the image to be built (eg. ghcr.io/seravo/myimage)'
    required: true
  tag:
    description: 'Tag for the image to be built (eg. latest)'
    required: true
  path:
    description: 'Build path for Docker (default: .)'
    required: true
    default: '.'
  dockerfile:
    description: 'Name of Dockerfile'
    required: true
    default: 'Dockerfile'
  cache:
    description: "Use cache"
    required: true
    default: "yes"
  default-cache:
    description: "Use cache from input image"
    required: true
    default: "yes"
  args:
    description: 'Additional arguments for Docker build. (eg. --build-arg NAME="NAME")'
    required: true
    default: ''

outputs:
  image-id:
    description: 'Docker Image ID for the image'
    value: ''

runs:
  using: composite
  steps:
    - id: docker-build-setup
      name: 'Setup a customer builder'
      shell: bash
      run: |
        docker buildx create \
          --name seravo-customer-builder \
          --driver docker-container

    - id: pull-git-tags
      if: ${{ github.ref_type != 'tag' }}
      name: 'Pull tags from git'
      shell: bash
      run: git fetch --tags

    - id: read-git-version
      name: 'Read version information with git'
      shell: bash
      run: echo "version=$(git describe --always)" >> $GITHUB_OUTPUT

    - id: read-features
      name: Read repository features
      uses: seravo/actions/features@v1.16.4

    - id: docker-build
      name: 'Build new image'
      run: |
        docker buildx --builder seravo-customer-builder build \
          --label "org.opencontainers.image.revision=${{ github.sha }}" \
          --label "org.opencontainers.image.version=${{ steps.read-git-version.outputs.version }}+${{ github.run_number }}.${{ github.run_id }}.${{ github.run_attempt }}" \
          --label 'com.seravo.features=${{ steps.read-features.outputs.features }}' \
          -f "${{ inputs.path }}/${{ inputs.dockerfile }}" \
          ${{ inputs.args }} \
          ${{ inputs.cache == 'no' && '--no-cache' || '' }} \
          ${{ inputs.default-cache == 'yes' && format('--cache-from {0}', inputs.image) || '' }} \
          --load \
          --tag "${{ inputs.image }}:${{ inputs.tag }}" \
          "${{ inputs.path }}"
      shell: bash
