---
name: 'Push Docker image'
description: 'Push Docker image to remote repository'

inputs:
  image:
    description: 'Name and tag for the image to be pushed'
    required: true

runs:
  using: composite
  steps:
    - id: list-images
      name: List images
      run: buildah images
      shell: bash

    - id: buildah-push
      name: 'Push image to repository'
      run: buildah push "${{ inputs.image }}"
      shell: bash
