---
name: "Run unittests"
description: "Run unitttests with pytest"

inputs:
  path:
    description: "Target path"
    required: true
    default: "tests"
  python_version:
    description: "Python version to use"
    required: true
    default: "3.10"
  requirements_path:
    description: "Path to a requirements.txt file"
    required: true
  dev_requirements_path:
    description: "Path to a dev-requirements.txt file"
    required: false

runs:
  using: composite
  steps:
    - id: setup
      name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: 'pip'

    - id: install
      name: Install dependencies
      env:
        dev_requirements_path: ${{ github.action_path }}/requirements.txt
      shell: bash
      run: >-
        pip3 install
        --require-hashes
        -r ${{ inputs.requirements_path }}
        -r ${{ inputs.dev_requirements_path || env.dev_requirements_path }}

    - id: check
      name: Check code formatting
      shell: bash
      run: pytest -v ${{ inputs.path }}
