---
name: 'Build and release Docker image'
description: 'Build Docker image from sources, and release it into GitHub package registry (ghcr.io)'

inputs:
  access-token:
    description: 'GitHub Access Token for authenticating to services'
    required: true
    default: ${{ github.token }}
  image:
    description: 'Name and tag for the image to be built'
    required: true
  path:
    description: 'Build path for Docker (default: .)'
    required: true
    default: '.'

outputs:
  image-id:
    description: 'Docker Image ID for the image'
    value: ''

runs:
  using: composite
  steps:
    - id: docker-login
      uses: seravo/actions/docker-login@split
      with:
        access-token: "${{ inputs.access-token }}"
    
    - id: docker-pull
      name: 'Try to fetch latest image to speed up builds'
      uses: seravo/actions/docker-pull@split
      with:
        image: "${{ inputs.image }}"
    
    - id: docker-build
      uses: seravo/actions/docker-build@split
      with:
        image: ${{ inputs.image }}
        path: ${{ inputs.path }}

    - id: docker-tag-job
      name: 'Tag image by job id'
      uses: seravo/actions/docker-tag@split
      with:
        source: "${{ inputs.image }}"
        target: "${{ inputs.image }}-${{ github.run_id }}"
    
    - id: docker-push
      name: 'Push image to ghcr.io...'
      uses: seravo/actions/docker-push@split
      with:
        image: ${{ inputs.image }}
    
    - id: docker-push-job
      name: 'Push image to ghcr.io...'
      uses: seravo/actions/docker-push@split
      with:
        image: "${{ inputs.image }}-${{ github_run_id }}"
