---
name: 'Build and release Docker image'
description: 'Build Docker image from sources, and release it into GitHub package registry (ghcr.io)'

inputs:
  image_name:
    description: 'Name of the image to build and release (eg. ghcr.io/seravo/wordpress)'
    required: true
  tag:
    description: 'Tag of the image to build and release (eg. latest)'
    required: true
  path:
    description: 'Build path for Docker (default: .)'
    required: false
    default: '.'
  args:
    description: 'Additional arguments for Docker build. (eg. --build-arg NAME="NAME")'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: docker-login
      uses: Seravo/actions/docker-login@v1.9.0
      name: Login to GitHub Container Registry

    # To speed up builds, try to use previously built image as cache source.
    - if: ${{ github.event_name != 'schedule' }}
      name: Pull previously built image
      id: docker-pull
      uses: Seravo/actions/docker-pull@v1.9.0
      with:
        image: ${{ inputs.image_name }}
      continue-on-error: true

    - name: Clean dashes from tag
      id: clean-tag
      shell: bash
      run: echo "tag=$(echo "${{ inputs.tag }}" |sed 's/\//-/g')" >> $GITHUB_OUTPUT

    - id: docker-build
      uses: Seravo/actions/docker-build@v1.9.0
      name: Build image
      with:
        image: "${{ inputs.image_name}}:${{ steps.clean-tag.outputs.tag }}"
        path: ${{ inputs.path }}
        args: ${{ inputs.args }}

    - name: Push new ${{ inputs.image_name}} image to registry
      id: docker-push-master
      uses: Seravo/actions/docker-push@v1.9.0
      with:
        image: "${{ inputs.image_name }}:${{ steps.clean-tag.outputs.tag }}"
