---
name: "Lint YAML files"

on: [push]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Run linting
        uses: seravo/actions/yamllint@v1.9.0
