---
name: "Lint YAML files"

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Run linting
        uses: seravo/actions/yamllint@v1.2.3
